drop table if exists endpoint_hits;


create table if not exists endpoint_hits (
    id bigint generated by default as identity PRIMARY KEY not null,
    app       varchar(255) not null,
    ip        varchar(255) not null,
    timestamp timestamp    not null,
    uri       varchar(255) not null
);

alter table endpoint_hits alter column id restart with 1;